# Generated by Django 5.0.2 on 2024-02-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_activite_hebergement_reservation_utilisateur_voyage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='Hebergement',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.DeleteModel(
            name='Voyage',
        ),
    ]
