# Generated by Django 5.0.2 on 2024-02-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_delete_activite_delete_hebergement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Personne',
        ),
    ]
