# Generated by Django 5.0.2 on 2024-02-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_activite_hebergement_voyage_remove_personne_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
