# Generated by Django 5.0.2 on 2024-02-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_personne_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='date_arrivee',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='date_depart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateTimeField(null=True),
        ),
    ]
