# Generated by Django 5.0.2 on 2024-02-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0010_delete_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModeTransport', models.IntegerField(unique=True)),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=255)),
                ('arriver', models.CharField(max_length=255)),
                ('heuredep', models.DateTimeField()),
                ('heurearriver', models.DateTimeField()),
                ('place', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idModeTransport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.modedetransport')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.utilisateur')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.voyage')),
            ],
        ),
    ]
