# Generated by Django 5.0.2 on 2024-02-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hebergement', models.CharField(max_length=100, null=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('date_depart', models.DateField(null=True)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField(null=True)),
                ('lieu_naissance', models.CharField(max_length=100, null=True)),
                ('adresse_rue', models.CharField(max_length=255, null=True)),
                ('adresse_ville', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='idModeTransport',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='voyage',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='arriver',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='heurearriver',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='heuredep',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='place',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='prix',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nb_passagers',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='moyen_transport',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.personne'),
        ),
        migrations.DeleteModel(
            name='ModeDeTransport',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
